name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/app"
          rm: false

      - name: Finalize Docker Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            echo "DB_USER=postgres" >> .env
            echo "DB_NAME=gametracker" >> .env

            docker compose up -d --build

            docker exec gametracker-ollama ollama pull llama3

            docker image prune -f